# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-03 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(default='Sin nombre', max_length=10, null=True)),
                ('Apellidos', models.CharField(default='Sin apellido', max_length=20, null=True)),
                ('Dni', models.CharField(default='Sin Dni', max_length=10, null=True)),
                ('Edad', models.IntegerField(default=0, null=True)),
                ('Telefono', models.CharField(default='0000', max_length=30, null=True)),
                ('Genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='----', max_length=300)),
                ('Gmail', models.EmailField(default='sin@datos.com', max_length=254, null=True)),
                ('Pais', models.CharField(choices=[('Nicaragua', 'Nicaragua'), ('Ecuador', 'Ecuador'), ('Perú', 'Perú'), ('Paraguay', 'Paraguay'), ('Uruguay', 'Uruguay'), ('Guatemala', 'Guatemala'), ('El Salvador', 'El Salvador'), ('Costa Rica', 'Costa Rica'), ('Colombia', 'Colombia'), ('Chile', 'Chile'), ('Bolivia', 'Bolivia'), ('Panamá', 'Panamá'), ('México', 'México'), ('Honduras', 'Honduras'), ('Haití', 'Haití'), ('República Dominicana', 'República Dominicana'), ('Argentina', 'Argentina'), ('Venezuela', 'Venezuela'), ('Brasil', 'Brasil')], default='----', max_length=300)),
                ('Address', models.TextField(default='Sin Datos', null=True)),
            ],
        ),
    ]
