# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-03 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='Pais',
            field=models.CharField(choices=[('Panamá', 'Panamá'), ('Perú', 'Perú'), ('Paraguay', 'Paraguay'), ('Haití', 'Haití'), ('El Salvador', 'El Salvador'), ('Ecuador', 'Ecuador'), ('Costa Rica', 'Costa Rica'), ('Uruguay', 'Uruguay'), ('Colombia', 'Colombia'), ('Venezuela', 'Venezuela'), ('México', 'México'), ('Honduras', 'Honduras'), ('Chile', 'Chile'), ('Bolivia', 'Bolivia'), ('Argentina', 'Argentina'), ('República Dominicana', 'República Dominicana'), ('Brasil', 'Brasil'), ('Nicaragua', 'Nicaragua'), ('Guatemala', 'Guatemala')], default='----', max_length=300),
        ),
    ]
