# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-04 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20190303_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Sin nombre', max_length=10, null=True)),
                ('Contrasena', models.CharField(default='False', max_length=10, null=True)),
                ('ContrasenaConfirmacion', models.CharField(default='False', max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='Pais',
            field=models.CharField(choices=[('Honduras', 'Honduras'), ('Paraguay', 'Paraguay'), ('Guatemala', 'Guatemala'), ('Panamá', 'Panamá'), ('Perú', 'Perú'), ('Colombia', 'Colombia'), ('Chile', 'Chile'), ('Bolivia', 'Bolivia'), ('Uruguay', 'Uruguay'), ('El Salvador', 'El Salvador'), ('Argentina', 'Argentina'), ('República Dominicana', 'República Dominicana'), ('Brasil', 'Brasil'), ('Haití', 'Haití'), ('Ecuador', 'Ecuador'), ('Costa Rica', 'Costa Rica'), ('Venezuela', 'Venezuela'), ('Nicaragua', 'Nicaragua'), ('México', 'México')], default='----', max_length=300),
        ),
    ]
