# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-13 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20190303_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='Pais',
            field=models.CharField(choices=[('República Dominicana', 'República Dominicana'), ('Paraguay', 'Paraguay'), ('Nicaragua', 'Nicaragua'), ('México', 'México'), ('Uruguay', 'Uruguay'), ('Haití', 'Haití'), ('Guatemala', 'Guatemala'), ('El Salvador', 'El Salvador'), ('Venezuela', 'Venezuela'), ('Perú', 'Perú'), ('Honduras', 'Honduras'), ('Ecuador', 'Ecuador'), ('Costa Rica', 'Costa Rica'), ('Colombia', 'Colombia'), ('Chile', 'Chile'), ('Brasil', 'Brasil'), ('Panamá', 'Panamá'), ('Bolivia', 'Bolivia'), ('Argentina', 'Argentina')], default='----', max_length=300),
        ),
    ]
